ALTER TABLE users
    ADD COLUMN IF NOT EXISTS last_login_ip VARCHAR(45) NULL,
    ADD COLUMN IF NOT EXISTS last_active_ip VARCHAR(45) NULL,
    ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS login_count INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_user_agent TEXT NULL,
    ADD COLUMN IF NOT EXISTS theme VARCHAR(20) NOT NULL DEFAULT 'light';
